#ifndef Global_h
#define Global_h

#include <irrlicht.h>

#define SH_SF SCREEN_HEIGHT / SCALE_FACTOR
#define SW_SF SCREEN_WIDTH / SCALE_FACTOR

using irr::f32;
using irr::u32;
using irr::s32;

#include "audiere.h"

using namespace audiere;

//static float SOUND_VOLUME = 0.0;
static AudioDevicePtr audioDevice = OpenDevice();

const u32 RESPONSE_TIME = 500;
const s32 ROCKET_ID = 1000;
const f32 ROCKET_SPEED = 0.4f;

const s32 ENEMY_CRAFT_THRESHOLD = -1000;

enum GAME_MODE {
	GAME_MODE_EASY = 701,
	GAME_MODE_NORMAL,
	GAME_MODE_HARD
};

struct SETTINGS_STRUCT {
	float soundVolume;
	GAME_MODE gameMode;
	SETTINGS_STRUCT() {
		soundVolume = 0.5;
		gameMode = GAME_MODE_EASY;
	}
};

const int SCREEN_WIDTH = 1024;
const int SCREEN_HEIGHT = 768;
const int SCALE_FACTOR = 4;

const f32 FIGHTER_SPEED = 5000.f;

const int BUTTON_WIDTH  = 494;
const int BUTTON_HEIGHT =  94;

const int ENEMY_BUFFER_HEIGHT = 25;

enum EXIT_NEWGAME_CONFIRM_DIALOG {
	EXIT_NEWGAME_YES = 10,
	EXIT_NEWGAME_NO,
};

enum EXIT_GAME_CONFIRM_DIALOG {
	EXIT_OK = 20,
	EXIT_CANCEL,
};

enum ENEMY_ID {
	BLINKY_ID = -1666,
	PINKY_ID,
	INKY_ID,
	CLYDE_ID
};

enum ENEMY_DIRECTION {
	ENEMY_LEFT = 0,
	ENEMY_RIGHT,
};

enum ENEMYWAVE_TYPE{
	ENEMYWAVE_EMPTY = -1,
	ENEMYWAVE_ENEMY_1,
	ENEMYWAVE_ENEMY_2,
	ENEMYWAVE_ENEMY_3,
	ENEMYWAVE_ENEMY_4,
	ENEMYWAVE_ASTEROID
};

enum GAME_STATE {
	GAME_MAINMENU_STATE = 101,
	GAME_NEWGAME_STATE,
	GAME_SETTINGS_STATE,
	GAME_HELP_STATE,
	GAME_ABOUT_STATE,
	GAME_GAMEOVER_STATE
};

enum NEWGAME_ELEMENT {
	NEWGAME_ROOT_NODE = 201,
	NEWGAME_BACKGROUND,
	NEWGAME_FIGHTER,
	NEWGAME_BACK_BUTTON,
	NEWGAME_PAUSE_BUTTON,
	NEWGAME_LEFT_TURBINE,
	NEWGAME_RIGHT_TURBINE
};

enum MAINMENU_ELEMENT {
	MAINMENU_ROOT_NODE = 301,
	MAINMENU_BACKGROUND,
	MAINMENU_FIGHTER,
	MAINMENU_TITLE,
	MAINMENU_NEW_GAME_BUTTON,
	MAINMENU_SETTINGS_BUTTON,
	MAINMENU_HELP_BUTTON,
	MAINMENU_ABOUT_BUTTON,
	MAINMENU_EXIT_BUTTON
};

enum ABOUT_ELEMENT {
	ABOUT_ROOT_NODE = 401,
	ABOUT_BACKGROUND,
	ABOUT_TITLE,
	ABOUT_BACK_BUTTON
};

enum SETTINGS_ELEMENT {
	SETTINGS_ROOT_NODE = 501,
	SETTINGS_BACKGROUND,
	SETTINGS_TITLE,
	SETTINGS_BACK_BUTTON,
	SETTINGS_COMBOBOX,
	SETTINGS_MODE_EASY,
	SETTINGS_MODE_NORMAL,
	SETTINGS_MODE_HARD,
	SETTINGS_SOUND_CHECKBOX,
};



#endif